/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../../common/index.js";
  

  export interface SlashingCallerInterface extends Interface {
    getFunction(nameOrSignature: "testUnjail"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "TestResult"): EventFragment;

    encodeFunctionData(functionFragment: 'testUnjail', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'testUnjail', data: BytesLike): Result;
  }

  
    export namespace TestResultEvent {
      export type InputTuple = [message: string, success: boolean];
      export type OutputTuple = [message: string, success: boolean];
      export interface OutputObject {message: string, success: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SlashingCaller extends BaseContract {
    
    connect(runner?: ContractRunner | null): SlashingCaller;
    waitForDeployment(): Promise<this>;

    interface: SlashingCallerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    testUnjail: TypedContractMethod<
      [validatorAddr: AddressLike, ],
      [boolean],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'testUnjail'): TypedContractMethod<
      [validatorAddr: AddressLike, ],
      [boolean],
      'nonpayable'
    >;

    getEvent(key: 'TestResult'): TypedContractEvent<TestResultEvent.InputTuple, TestResultEvent.OutputTuple, TestResultEvent.OutputObject>;

    filters: {
      
      'TestResult(string,bool)': TypedContractEvent<TestResultEvent.InputTuple, TestResultEvent.OutputTuple, TestResultEvent.OutputObject>;
      TestResult: TypedContractEvent<TestResultEvent.InputTuple, TestResultEvent.OutputTuple, TestResultEvent.OutputObject>;
    
    };
  }