/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../../common/index.js";
  import type { SlashingCaller, SlashingCallerInterface } from "../../../../cosmos/slashing/testdata/SlashingCaller";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "string",
        "name": "message",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "success",
        "type": "bool"
      }
    ],
    "name": "TestResult",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "validatorAddr",
        "type": "address"
      }
    ],
    "name": "testUnjail",
    "outputs": [
      {
        "internalType": "bool",
        "name": "success",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608060405234801561001057600080fd5b50610266806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80637327af9014610030575b600080fd5b61004a6004803603810190610045919061014a565b610060565b6040516100579190610192565b60405180910390f35b600061080673ffffffffffffffffffffffffffffffffffffffff1663449ecfe6836040518263ffffffff1660e01b815260040161009d91906101bc565b6020604051808303816000875af11580156100bc573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906100e09190610203565b9050919050565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6000610117826100ec565b9050919050565b6101278161010c565b811461013257600080fd5b50565b6000813590506101448161011e565b92915050565b6000602082840312156101605761015f6100e7565b5b600061016e84828501610135565b91505092915050565b60008115159050919050565b61018c81610177565b82525050565b60006020820190506101a76000830184610183565b92915050565b6101b68161010c565b82525050565b60006020820190506101d160008301846101ad565b92915050565b6101e081610177565b81146101eb57600080fd5b50565b6000815190506101fd816101d7565b92915050565b600060208284031215610219576102186100e7565b5b6000610227848285016101ee565b9150509291505056fea2646970667358221220ab0d2f21d6b97e44ff5ad34eae01c08b8a00f0290f160b20329e5672c6ad06b364736f6c63430008120033";

  
      type SlashingCallerConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: SlashingCallerConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class SlashingCaller__factory extends ContractFactory {
    
      constructor(...args: SlashingCallerConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<SlashingCaller & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): SlashingCaller__factory {
      return super.connect(runner) as SlashingCaller__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): SlashingCallerInterface {
      return new Interface(_abi) as SlashingCallerInterface;
    }
    
    override attach(address: string | Addressable): SlashingCaller {
      return super.attach(address) as SlashingCaller;
    }
  static connect(address: string, runner?: ContractRunner | null): SlashingCaller {
      return new Contract(address, _abi, runner) as unknown as SlashingCaller;
    }
  }

  
  