/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common/index.js";
  

  export interface Bech32IInterface extends Interface {
    getFunction(nameOrSignature: "bech32ToHex" | "hexToBech32"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'bech32ToHex', values: [string]): string;
encodeFunctionData(functionFragment: 'hexToBech32', values: [AddressLike, string]): string;

    decodeFunctionResult(functionFragment: 'bech32ToHex', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hexToBech32', data: BytesLike): Result;
  }

  

  export interface Bech32I extends BaseContract {
    
    connect(runner?: ContractRunner | null): Bech32I;
    waitForDeployment(): Promise<this>;

    interface: Bech32IInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    bech32ToHex: TypedContractMethod<
      [bech32Address: string, ],
      [string],
      'nonpayable'
    >
    

    
    hexToBech32: TypedContractMethod<
      [addr: AddressLike, prefix: string, ],
      [string],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'bech32ToHex'): TypedContractMethod<
      [bech32Address: string, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hexToBech32'): TypedContractMethod<
      [addr: AddressLike, prefix: string, ],
      [string],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }