// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: xpla/xatp/v1beta1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is the request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5460f2a2500350b0, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is the response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params defines the parameters of the module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5460f2a2500350b0, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryXatpsRequest struct {
}

func (m *QueryXatpsRequest) Reset()         { *m = QueryXatpsRequest{} }
func (m *QueryXatpsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryXatpsRequest) ProtoMessage()    {}
func (*QueryXatpsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5460f2a2500350b0, []int{2}
}
func (m *QueryXatpsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryXatpsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryXatpsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryXatpsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryXatpsRequest.Merge(m, src)
}
func (m *QueryXatpsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryXatpsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryXatpsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryXatpsRequest proto.InternalMessageInfo

type QueryXatpsResponse struct {
	Xatps []XATP `protobuf:"bytes,1,rep,name=xatps,proto3" json:"xatps"`
}

func (m *QueryXatpsResponse) Reset()         { *m = QueryXatpsResponse{} }
func (m *QueryXatpsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryXatpsResponse) ProtoMessage()    {}
func (*QueryXatpsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5460f2a2500350b0, []int{3}
}
func (m *QueryXatpsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryXatpsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryXatpsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryXatpsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryXatpsResponse.Merge(m, src)
}
func (m *QueryXatpsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryXatpsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryXatpsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryXatpsResponse proto.InternalMessageInfo

func (m *QueryXatpsResponse) GetXatps() []XATP {
	if m != nil {
		return m.Xatps
	}
	return nil
}

type QueryXatpRequest struct {
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
}

func (m *QueryXatpRequest) Reset()         { *m = QueryXatpRequest{} }
func (m *QueryXatpRequest) String() string { return proto.CompactTextString(m) }
func (*QueryXatpRequest) ProtoMessage()    {}
func (*QueryXatpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5460f2a2500350b0, []int{4}
}
func (m *QueryXatpRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryXatpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryXatpRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryXatpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryXatpRequest.Merge(m, src)
}
func (m *QueryXatpRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryXatpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryXatpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryXatpRequest proto.InternalMessageInfo

func (m *QueryXatpRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

type QueryXatpResponse struct {
	Xatp XATP `protobuf:"bytes,1,opt,name=xatp,proto3" json:"xatp"`
}

func (m *QueryXatpResponse) Reset()         { *m = QueryXatpResponse{} }
func (m *QueryXatpResponse) String() string { return proto.CompactTextString(m) }
func (*QueryXatpResponse) ProtoMessage()    {}
func (*QueryXatpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5460f2a2500350b0, []int{5}
}
func (m *QueryXatpResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryXatpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryXatpResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryXatpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryXatpResponse.Merge(m, src)
}
func (m *QueryXatpResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryXatpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryXatpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryXatpResponse proto.InternalMessageInfo

func (m *QueryXatpResponse) GetXatp() XATP {
	if m != nil {
		return m.Xatp
	}
	return XATP{}
}

// QueryXatpPoolRequest is the request type for the Query/XatpPool RPC
// method.
type QueryXatpPoolRequest struct {
}

func (m *QueryXatpPoolRequest) Reset()         { *m = QueryXatpPoolRequest{} }
func (m *QueryXatpPoolRequest) String() string { return proto.CompactTextString(m) }
func (*QueryXatpPoolRequest) ProtoMessage()    {}
func (*QueryXatpPoolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5460f2a2500350b0, []int{6}
}
func (m *QueryXatpPoolRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryXatpPoolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryXatpPoolRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryXatpPoolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryXatpPoolRequest.Merge(m, src)
}
func (m *QueryXatpPoolRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryXatpPoolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryXatpPoolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryXatpPoolRequest proto.InternalMessageInfo

// QueryXatpPoolResponse is the response type for the Query/XatpPool
// RPC method.
type QueryXatpPoolResponse struct {
	// pool defines community pool's coins.
	Pool github_com_cosmos_cosmos_sdk_types.DecCoins `protobuf:"bytes,1,rep,name=pool,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.DecCoins" json:"pool"`
}

func (m *QueryXatpPoolResponse) Reset()         { *m = QueryXatpPoolResponse{} }
func (m *QueryXatpPoolResponse) String() string { return proto.CompactTextString(m) }
func (*QueryXatpPoolResponse) ProtoMessage()    {}
func (*QueryXatpPoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5460f2a2500350b0, []int{7}
}
func (m *QueryXatpPoolResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryXatpPoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryXatpPoolResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryXatpPoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryXatpPoolResponse.Merge(m, src)
}
func (m *QueryXatpPoolResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryXatpPoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryXatpPoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryXatpPoolResponse proto.InternalMessageInfo

func (m *QueryXatpPoolResponse) GetPool() github_com_cosmos_cosmos_sdk_types.DecCoins {
	if m != nil {
		return m.Pool
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "xpla.xatp.v1beta1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "xpla.xatp.v1beta1.QueryParamsResponse")
	proto.RegisterType((*QueryXatpsRequest)(nil), "xpla.xatp.v1beta1.QueryXatpsRequest")
	proto.RegisterType((*QueryXatpsResponse)(nil), "xpla.xatp.v1beta1.QueryXatpsResponse")
	proto.RegisterType((*QueryXatpRequest)(nil), "xpla.xatp.v1beta1.QueryXatpRequest")
	proto.RegisterType((*QueryXatpResponse)(nil), "xpla.xatp.v1beta1.QueryXatpResponse")
	proto.RegisterType((*QueryXatpPoolRequest)(nil), "xpla.xatp.v1beta1.QueryXatpPoolRequest")
	proto.RegisterType((*QueryXatpPoolResponse)(nil), "xpla.xatp.v1beta1.QueryXatpPoolResponse")
}

func init() { proto.RegisterFile("xpla/xatp/v1beta1/query.proto", fileDescriptor_5460f2a2500350b0) }

var fileDescriptor_5460f2a2500350b0 = []byte{
	// 531 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0x4f, 0x6f, 0x12, 0x41,
	0x18, 0xc6, 0x59, 0x0b, 0x44, 0xa7, 0x17, 0x3b, 0x45, 0x6d, 0x57, 0x5c, 0xda, 0x95, 0x5a, 0x12,
	0xe3, 0x4e, 0x80, 0x83, 0x37, 0x13, 0xd1, 0x98, 0x78, 0x31, 0x48, 0x3c, 0x34, 0x5e, 0xcc, 0x00,
	0x93, 0x75, 0x23, 0xec, 0x3b, 0x65, 0x06, 0xd2, 0xd6, 0xe8, 0x41, 0xbf, 0x80, 0x89, 0xdf, 0xc2,
	0x4f, 0xd2, 0x63, 0x13, 0x2f, 0x9e, 0xd4, 0x80, 0x5f, 0xc3, 0xc4, 0xcc, 0x9f, 0xdd, 0x60, 0xf9,
	0xb3, 0x27, 0xe0, 0x7d, 0x9f, 0x79, 0x7e, 0xef, 0x9b, 0xe7, 0x0d, 0xe8, 0xce, 0x09, 0x1f, 0x50,
	0x72, 0x42, 0x25, 0x27, 0x93, 0x7a, 0x97, 0x49, 0x5a, 0x27, 0xc7, 0x63, 0x36, 0x3a, 0x0d, 0xf8,
	0x08, 0x24, 0xe0, 0x2d, 0xd5, 0x0e, 0x54, 0x3b, 0xb0, 0x6d, 0xb7, 0x14, 0x42, 0x08, 0xba, 0x4b,
	0xd4, 0x37, 0x23, 0x74, 0xcb, 0x21, 0x40, 0x38, 0x60, 0x84, 0xf2, 0x88, 0xd0, 0x38, 0x06, 0x49,
	0x65, 0x04, 0xb1, 0x48, 0xba, 0x8b, 0x14, 0xed, 0x69, 0xba, 0x5e, 0x0f, 0xc4, 0x10, 0x04, 0xe9,
	0x52, 0xc1, 0xd2, 0x7e, 0x0f, 0xa2, 0xd8, 0xf4, 0xfd, 0x12, 0xc2, 0x2f, 0xd5, 0x4c, 0x6d, 0x3a,
	0xa2, 0x43, 0xd1, 0x61, 0xc7, 0x63, 0x26, 0xa4, 0xff, 0x02, 0x6d, 0xff, 0x57, 0x15, 0x1c, 0x62,
	0xc1, 0xf0, 0x43, 0x54, 0xe4, 0xba, 0xb2, 0xe3, 0xec, 0x39, 0xb5, 0xcd, 0xc6, 0x6e, 0xb0, 0xb0,
	0x42, 0x60, 0x9e, 0xb4, 0xf2, 0xe7, 0x3f, 0x2b, 0xb9, 0x8e, 0x95, 0xfb, 0xdb, 0x68, 0x4b, 0xfb,
	0x1d, 0x51, 0xc9, 0x53, 0xc8, 0x73, 0x8b, 0xb6, 0x45, 0xcb, 0x68, 0xa2, 0x82, 0xf2, 0x53, 0x88,
	0x8d, 0xda, 0x66, 0xe3, 0xd6, 0x12, 0xc4, 0xd1, 0xe3, 0x57, 0x6d, 0x0b, 0x30, 0x5a, 0xbf, 0x86,
	0xae, 0xa7, 0x56, 0xd6, 0x1e, 0x97, 0x50, 0xa1, 0xcf, 0x62, 0x18, 0xea, 0x59, 0xaf, 0x75, 0xcc,
	0x0f, 0xff, 0xd9, 0xdc, 0x24, 0x29, 0xb3, 0x8e, 0xf2, 0xca, 0xc7, 0x6e, 0x95, 0x81, 0xd4, 0x52,
	0xff, 0x26, 0x2a, 0xa5, 0x3e, 0x6d, 0x80, 0x41, 0xb2, 0xd4, 0x47, 0x74, 0xe3, 0x52, 0xdd, 0x32,
	0x18, 0xca, 0x73, 0x80, 0x81, 0x5d, 0xab, 0x1c, 0x98, 0x5c, 0x02, 0x95, 0x4b, 0x4a, 0x79, 0xca,
	0x7a, 0x4f, 0x20, 0x8a, 0x5b, 0x4d, 0x05, 0xfa, 0xf6, 0xab, 0x72, 0x3f, 0x8c, 0xe4, 0xdb, 0x71,
	0x37, 0xe8, 0xc1, 0x90, 0xd8, 0x1c, 0xcd, 0xc7, 0x03, 0xd1, 0x7f, 0x47, 0xe4, 0x29, 0x67, 0x22,
	0x79, 0x23, 0x3a, 0xda, 0xbe, 0xf1, 0x77, 0x03, 0x15, 0xf4, 0x00, 0xf8, 0x0c, 0x15, 0x4d, 0x16,
	0xf8, 0x60, 0xc9, 0x42, 0x8b, 0xa1, 0xbb, 0xf7, 0xb2, 0x64, 0x66, 0x13, 0x7f, 0xff, 0xd3, 0xf7,
	0x3f, 0x5f, 0xaf, 0xdc, 0xc6, 0xbb, 0x64, 0xf1, 0xf2, 0x4c, 0xde, 0x78, 0x82, 0x0a, 0x3a, 0x55,
	0x5c, 0x5d, 0xe5, 0x39, 0x7f, 0x09, 0xee, 0x41, 0x86, 0xca, 0x82, 0xf7, 0x34, 0xd8, 0xc5, 0x3b,
	0x64, 0xf9, 0xc9, 0x0b, 0x7c, 0x86, 0xf2, 0xea, 0x09, 0xbe, 0xbb, 0xce, 0x30, 0xa1, 0x56, 0xd7,
	0x8b, 0x2c, 0xf4, 0x50, 0x43, 0xf7, 0x71, 0x65, 0x05, 0x94, 0xbc, 0xd7, 0x87, 0xf5, 0x01, 0x7f,
	0x76, 0xd0, 0xd5, 0x24, 0x75, 0x7c, 0xb8, 0xce, 0x7b, 0xee, 0x5e, 0xdc, 0x5a, 0xb6, 0xd0, 0x0e,
	0x52, 0xd5, 0x83, 0x78, 0xb8, 0xbc, 0x62, 0x90, 0x37, 0x2a, 0xff, 0xd6, 0xa3, 0xf3, 0xa9, 0xe7,
	0x5c, 0x4c, 0x3d, 0xe7, 0xf7, 0xd4, 0x73, 0xbe, 0xcc, 0xbc, 0xdc, 0xc5, 0xcc, 0xcb, 0xfd, 0x98,
	0x79, 0xb9, 0xd7, 0xd5, 0xb9, 0x63, 0x52, 0x0e, 0x7d, 0x36, 0xb1, 0x4e, 0xc6, 0x4b, 0x9f, 0x53,
	0xb7, 0xa8, 0xff, 0x16, 0x9a, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x22, 0x97, 0x17, 0xbc,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params queries params of the cw20 module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	Xatps(ctx context.Context, in *QueryXatpsRequest, opts ...grpc.CallOption) (*QueryXatpsResponse, error)
	Xatp(ctx context.Context, in *QueryXatpRequest, opts ...grpc.CallOption) (*QueryXatpResponse, error)
	// XatpPool queries the Xatp pool coins.
	XatpPool(ctx context.Context, in *QueryXatpPoolRequest, opts ...grpc.CallOption) (*QueryXatpPoolResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/xpla.xatp.v1beta1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Xatps(ctx context.Context, in *QueryXatpsRequest, opts ...grpc.CallOption) (*QueryXatpsResponse, error) {
	out := new(QueryXatpsResponse)
	err := c.cc.Invoke(ctx, "/xpla.xatp.v1beta1.Query/Xatps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Xatp(ctx context.Context, in *QueryXatpRequest, opts ...grpc.CallOption) (*QueryXatpResponse, error) {
	out := new(QueryXatpResponse)
	err := c.cc.Invoke(ctx, "/xpla.xatp.v1beta1.Query/Xatp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) XatpPool(ctx context.Context, in *QueryXatpPoolRequest, opts ...grpc.CallOption) (*QueryXatpPoolResponse, error) {
	out := new(QueryXatpPoolResponse)
	err := c.cc.Invoke(ctx, "/xpla.xatp.v1beta1.Query/XatpPool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params queries params of the cw20 module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	Xatps(context.Context, *QueryXatpsRequest) (*QueryXatpsResponse, error)
	Xatp(context.Context, *QueryXatpRequest) (*QueryXatpResponse, error)
	// XatpPool queries the Xatp pool coins.
	XatpPool(context.Context, *QueryXatpPoolRequest) (*QueryXatpPoolResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Xatps(ctx context.Context, req *QueryXatpsRequest) (*QueryXatpsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Xatps not implemented")
}
func (*UnimplementedQueryServer) Xatp(ctx context.Context, req *QueryXatpRequest) (*QueryXatpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Xatp not implemented")
}
func (*UnimplementedQueryServer) XatpPool(ctx context.Context, req *QueryXatpPoolRequest) (*QueryXatpPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method XatpPool not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xpla.xatp.v1beta1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Xatps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryXatpsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Xatps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xpla.xatp.v1beta1.Query/Xatps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Xatps(ctx, req.(*QueryXatpsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Xatp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryXatpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Xatp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xpla.xatp.v1beta1.Query/Xatp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Xatp(ctx, req.(*QueryXatpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_XatpPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryXatpPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).XatpPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xpla.xatp.v1beta1.Query/XatpPool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).XatpPool(ctx, req.(*QueryXatpPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "xpla.xatp.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Xatps",
			Handler:    _Query_Xatps_Handler,
		},
		{
			MethodName: "Xatp",
			Handler:    _Query_Xatp_Handler,
		},
		{
			MethodName: "XatpPool",
			Handler:    _Query_XatpPool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xpla/xatp/v1beta1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryXatpsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryXatpsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryXatpsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryXatpsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryXatpsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryXatpsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Xatps) > 0 {
		for iNdEx := len(m.Xatps) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Xatps[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryXatpRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryXatpRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryXatpRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryXatpResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryXatpResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryXatpResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Xatp.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryXatpPoolRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryXatpPoolRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryXatpPoolRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryXatpPoolResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryXatpPoolResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryXatpPoolResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Pool) > 0 {
		for iNdEx := len(m.Pool) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Pool[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryXatpsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryXatpsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Xatps) > 0 {
		for _, e := range m.Xatps {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryXatpRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryXatpResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Xatp.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryXatpPoolRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryXatpPoolResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Pool) > 0 {
		for _, e := range m.Pool {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryXatpsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryXatpsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryXatpsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryXatpsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryXatpsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryXatpsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Xatps", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Xatps = append(m.Xatps, XATP{})
			if err := m.Xatps[len(m.Xatps)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryXatpRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryXatpRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryXatpRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryXatpResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryXatpResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryXatpResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Xatp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Xatp.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryXatpPoolRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryXatpPoolRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryXatpPoolRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryXatpPoolResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryXatpPoolResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryXatpPoolResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pool", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pool = append(m.Pool, types.DecCoin{})
			if err := m.Pool[len(m.Pool)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
