// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: xpla/burn/v1beta1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryOngoingProposalsRequest is the request type for the
// Query/OngoingProposals RPC method.
type QueryOngoingProposalsRequest struct {
	// pagination defines an optional pagination for the request.
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryOngoingProposalsRequest) Reset()         { *m = QueryOngoingProposalsRequest{} }
func (m *QueryOngoingProposalsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryOngoingProposalsRequest) ProtoMessage()    {}
func (*QueryOngoingProposalsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e1f598c4880bf1f, []int{0}
}
func (m *QueryOngoingProposalsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryOngoingProposalsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryOngoingProposalsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryOngoingProposalsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOngoingProposalsRequest.Merge(m, src)
}
func (m *QueryOngoingProposalsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryOngoingProposalsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOngoingProposalsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOngoingProposalsRequest proto.InternalMessageInfo

func (m *QueryOngoingProposalsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryOngoingProposalsResponse is the response type for the
// Query/OngoingProposals RPC method.
type QueryOngoingProposalsResponse struct {
	Proposals []BurnProposal `protobuf:"bytes,1,rep,name=proposals,proto3" json:"proposals"`
	// pagination defines the pagination in the response.
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryOngoingProposalsResponse) Reset()         { *m = QueryOngoingProposalsResponse{} }
func (m *QueryOngoingProposalsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryOngoingProposalsResponse) ProtoMessage()    {}
func (*QueryOngoingProposalsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e1f598c4880bf1f, []int{1}
}
func (m *QueryOngoingProposalsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryOngoingProposalsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryOngoingProposalsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryOngoingProposalsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOngoingProposalsResponse.Merge(m, src)
}
func (m *QueryOngoingProposalsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryOngoingProposalsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOngoingProposalsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOngoingProposalsResponse proto.InternalMessageInfo

func (m *QueryOngoingProposalsResponse) GetProposals() []BurnProposal {
	if m != nil {
		return m.Proposals
	}
	return nil
}

func (m *QueryOngoingProposalsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryOngoingProposalRequest is the request type for the Query/OngoingProposal
// RPC method.
type QueryOngoingProposalRequest struct {
	ProposalId uint64 `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
}

func (m *QueryOngoingProposalRequest) Reset()         { *m = QueryOngoingProposalRequest{} }
func (m *QueryOngoingProposalRequest) String() string { return proto.CompactTextString(m) }
func (*QueryOngoingProposalRequest) ProtoMessage()    {}
func (*QueryOngoingProposalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e1f598c4880bf1f, []int{2}
}
func (m *QueryOngoingProposalRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryOngoingProposalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryOngoingProposalRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryOngoingProposalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOngoingProposalRequest.Merge(m, src)
}
func (m *QueryOngoingProposalRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryOngoingProposalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOngoingProposalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOngoingProposalRequest proto.InternalMessageInfo

func (m *QueryOngoingProposalRequest) GetProposalId() uint64 {
	if m != nil {
		return m.ProposalId
	}
	return 0
}

// QueryOngoingProposalResponse is the response type for the
// Query/OngoingProposal RPC method.
type QueryOngoingProposalResponse struct {
	Proposer string                                   `protobuf:"bytes,1,opt,name=proposer,proto3" json:"proposer,omitempty"`
	Amount   github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=amount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"amount"`
}

func (m *QueryOngoingProposalResponse) Reset()         { *m = QueryOngoingProposalResponse{} }
func (m *QueryOngoingProposalResponse) String() string { return proto.CompactTextString(m) }
func (*QueryOngoingProposalResponse) ProtoMessage()    {}
func (*QueryOngoingProposalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e1f598c4880bf1f, []int{3}
}
func (m *QueryOngoingProposalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryOngoingProposalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryOngoingProposalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryOngoingProposalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOngoingProposalResponse.Merge(m, src)
}
func (m *QueryOngoingProposalResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryOngoingProposalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOngoingProposalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOngoingProposalResponse proto.InternalMessageInfo

func (m *QueryOngoingProposalResponse) GetProposer() string {
	if m != nil {
		return m.Proposer
	}
	return ""
}

func (m *QueryOngoingProposalResponse) GetAmount() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Amount
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryOngoingProposalsRequest)(nil), "xpla.burn.v1beta1.QueryOngoingProposalsRequest")
	proto.RegisterType((*QueryOngoingProposalsResponse)(nil), "xpla.burn.v1beta1.QueryOngoingProposalsResponse")
	proto.RegisterType((*QueryOngoingProposalRequest)(nil), "xpla.burn.v1beta1.QueryOngoingProposalRequest")
	proto.RegisterType((*QueryOngoingProposalResponse)(nil), "xpla.burn.v1beta1.QueryOngoingProposalResponse")
}

func init() { proto.RegisterFile("xpla/burn/v1beta1/query.proto", fileDescriptor_6e1f598c4880bf1f) }

var fileDescriptor_6e1f598c4880bf1f = []byte{
	// 546 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x3f, 0x6f, 0x13, 0x3f,
	0x18, 0xc7, 0xe3, 0xfc, 0xfa, 0xab, 0xa8, 0x33, 0x40, 0x4f, 0x1d, 0xd2, 0x90, 0x5e, 0xaa, 0x50,
	0x4a, 0x54, 0xe8, 0x99, 0x06, 0x58, 0x2b, 0x91, 0x4a, 0x20, 0x26, 0xca, 0xb1, 0xb1, 0x44, 0xbe,
	0x9c, 0x71, 0x2d, 0x12, 0x3f, 0xd7, 0xf3, 0x5d, 0xd5, 0xae, 0xbc, 0x02, 0x24, 0x5e, 0x00, 0x03,
	0x0b, 0x42, 0x42, 0x62, 0x60, 0x66, 0xee, 0x46, 0x05, 0x0b, 0x13, 0xa0, 0x04, 0x89, 0xb7, 0x81,
	0xce, 0xf6, 0xe5, 0x4f, 0x13, 0x20, 0x4b, 0x72, 0xe7, 0xe7, 0xfb, 0x7d, 0xfc, 0xf1, 0xf7, 0xf1,
	0xe1, 0xb5, 0xe3, 0xa8, 0x4b, 0x49, 0x90, 0xc6, 0x92, 0x1c, 0xed, 0x04, 0x2c, 0xa1, 0x3b, 0xe4,
	0x30, 0x65, 0xf1, 0x89, 0x17, 0xc5, 0x90, 0x80, 0xb3, 0x9c, 0x95, 0xbd, 0xac, 0xec, 0xd9, 0x72,
	0x65, 0x85, 0x03, 0x07, 0x5d, 0x25, 0xd9, 0x93, 0x11, 0x56, 0xaa, 0x1c, 0x80, 0x77, 0x19, 0xa1,
	0x91, 0x20, 0x54, 0x4a, 0x48, 0x68, 0x22, 0x40, 0x2a, 0x5b, 0xdd, 0xea, 0x80, 0xea, 0x81, 0x22,
	0x01, 0x55, 0xcc, 0xf4, 0x1f, 0xee, 0x16, 0x51, 0x2e, 0xa4, 0x16, 0x5b, 0xad, 0x3b, 0xae, 0xcd,
	0x55, 0x1d, 0x10, 0x79, 0xbd, 0x3a, 0x4d, 0xac, 0xf9, 0x4c, 0x75, 0xd5, 0xb8, 0xdb, 0x06, 0xd0,
	0xbc, 0xd8, 0xd2, 0x32, 0xed, 0x09, 0x09, 0x44, 0xff, 0x9a, 0xa5, 0xfa, 0x53, 0x5c, 0x7d, 0x94,
	0xd1, 0x3c, 0x94, 0x1c, 0x84, 0xe4, 0xfb, 0x31, 0x44, 0xa0, 0x68, 0x57, 0xf9, 0xec, 0x30, 0x65,
	0x2a, 0x71, 0xee, 0x61, 0x3c, 0xe2, 0x2b, 0xa3, 0x75, 0xd4, 0x28, 0x35, 0x37, 0x3d, 0xdb, 0x35,
	0x03, 0xf4, 0x4c, 0x58, 0x16, 0xc4, 0xdb, 0xa7, 0x9c, 0x59, 0xaf, 0x3f, 0xe6, 0xac, 0xbf, 0x43,
	0x78, 0xed, 0x0f, 0x1b, 0xa9, 0x08, 0xa4, 0x62, 0xce, 0x1e, 0x5e, 0x8a, 0xf2, 0xc5, 0x32, 0x5a,
	0xff, 0xaf, 0x51, 0x6a, 0xd6, 0xbc, 0xa9, 0xf0, 0xbd, 0x56, 0x1a, 0xcb, 0xdc, 0xdc, 0x5a, 0x38,
	0xfd, 0x56, 0x2b, 0xf8, 0x23, 0x9f, 0x73, 0x7f, 0x02, 0xb7, 0xa8, 0x71, 0xaf, 0xfd, 0x13, 0xd7,
	0x10, 0x4c, 0xf0, 0xee, 0xe2, 0xcb, 0xb3, 0x70, 0xf3, 0x58, 0x6a, 0xb8, 0x94, 0x6f, 0xda, 0x16,
	0xa1, 0xce, 0x65, 0xc1, 0xc7, 0xf9, 0xd2, 0x83, 0xb0, 0xfe, 0x11, 0xcd, 0x0e, 0x76, 0x78, 0xdc,
	0xdb, 0xf8, 0x82, 0x91, 0xb3, 0x58, 0xdb, 0x97, 0x5a, 0xe5, 0xcf, 0x1f, 0xb6, 0x57, 0x2c, 0xea,
	0xdd, 0x30, 0x8c, 0x99, 0x52, 0x8f, 0x93, 0x58, 0x48, 0xee, 0x0f, 0x95, 0xce, 0x01, 0x5e, 0xa4,
	0x3d, 0x48, 0x65, 0x52, 0x2e, 0xea, 0x84, 0x56, 0x27, 0xce, 0x96, 0x9f, 0x6a, 0x0f, 0x84, 0x6c,
	0xdd, 0xc9, 0xb2, 0x79, 0xfb, 0xbd, 0xd6, 0xe0, 0x22, 0x39, 0x48, 0x03, 0xaf, 0x03, 0x3d, 0x7b,
	0x1b, 0xec, 0xdf, 0xb6, 0x0a, 0x9f, 0x91, 0xe4, 0x24, 0x62, 0x4a, 0x1b, 0xd4, 0x9b, 0x5f, 0xef,
	0xb7, 0x90, 0x6f, 0xfb, 0x37, 0x3f, 0x15, 0xf1, 0xff, 0xfa, 0x00, 0xce, 0x6b, 0x84, 0x2f, 0x9d,
	0x9f, 0x9a, 0x43, 0x66, 0x8c, 0xe6, 0x6f, 0x17, 0xa9, 0x72, 0x73, 0x7e, 0x83, 0x49, 0xa8, 0x7e,
	0xe3, 0xf9, 0x97, 0x9f, 0x2f, 0x8b, 0x9b, 0xce, 0x06, 0x99, 0xbe, 0xef, 0x60, 0x4c, 0xed, 0xd1,
	0xe4, 0x5f, 0x21, 0x7c, 0xf1, 0x5c, 0x2b, 0xc7, 0x9b, 0x73, 0xcf, 0x9c, 0x91, 0xcc, 0xad, 0xb7,
	0x88, 0xd7, 0x35, 0xe2, 0x55, 0xe7, 0xca, 0x1c, 0x88, 0xad, 0xdd, 0xd3, 0xbe, 0x8b, 0xce, 0xfa,
	0x2e, 0xfa, 0xd1, 0x77, 0xd1, 0x8b, 0x81, 0x5b, 0x38, 0x1b, 0xb8, 0x85, 0xaf, 0x03, 0xb7, 0xf0,
	0x64, 0x63, 0x6c, 0x44, 0x59, 0xa3, 0x90, 0x1d, 0x99, 0x86, 0xc7, 0xa6, 0xa5, 0x1e, 0x52, 0xb0,
	0xa8, 0xbf, 0xd8, 0x5b, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x81, 0x77, 0x5c, 0xb1, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Query all ongoing burn proposals
	OngoingProposals(ctx context.Context, in *QueryOngoingProposalsRequest, opts ...grpc.CallOption) (*QueryOngoingProposalsResponse, error)
	// Query a specific ongoing burn proposal by ID
	OngoingProposal(ctx context.Context, in *QueryOngoingProposalRequest, opts ...grpc.CallOption) (*QueryOngoingProposalResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) OngoingProposals(ctx context.Context, in *QueryOngoingProposalsRequest, opts ...grpc.CallOption) (*QueryOngoingProposalsResponse, error) {
	out := new(QueryOngoingProposalsResponse)
	err := c.cc.Invoke(ctx, "/xpla.burn.v1beta1.Query/OngoingProposals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) OngoingProposal(ctx context.Context, in *QueryOngoingProposalRequest, opts ...grpc.CallOption) (*QueryOngoingProposalResponse, error) {
	out := new(QueryOngoingProposalResponse)
	err := c.cc.Invoke(ctx, "/xpla.burn.v1beta1.Query/OngoingProposal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Query all ongoing burn proposals
	OngoingProposals(context.Context, *QueryOngoingProposalsRequest) (*QueryOngoingProposalsResponse, error)
	// Query a specific ongoing burn proposal by ID
	OngoingProposal(context.Context, *QueryOngoingProposalRequest) (*QueryOngoingProposalResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) OngoingProposals(ctx context.Context, req *QueryOngoingProposalsRequest) (*QueryOngoingProposalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OngoingProposals not implemented")
}
func (*UnimplementedQueryServer) OngoingProposal(ctx context.Context, req *QueryOngoingProposalRequest) (*QueryOngoingProposalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OngoingProposal not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_OngoingProposals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOngoingProposalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).OngoingProposals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xpla.burn.v1beta1.Query/OngoingProposals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).OngoingProposals(ctx, req.(*QueryOngoingProposalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_OngoingProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOngoingProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).OngoingProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xpla.burn.v1beta1.Query/OngoingProposal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).OngoingProposal(ctx, req.(*QueryOngoingProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "xpla.burn.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OngoingProposals",
			Handler:    _Query_OngoingProposals_Handler,
		},
		{
			MethodName: "OngoingProposal",
			Handler:    _Query_OngoingProposal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xpla/burn/v1beta1/query.proto",
}

func (m *QueryOngoingProposalsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryOngoingProposalsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryOngoingProposalsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryOngoingProposalsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryOngoingProposalsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryOngoingProposalsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Proposals) > 0 {
		for iNdEx := len(m.Proposals) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Proposals[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryOngoingProposalRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryOngoingProposalRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryOngoingProposalRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ProposalId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ProposalId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryOngoingProposalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryOngoingProposalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryOngoingProposalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		for iNdEx := len(m.Amount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Amount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Proposer) > 0 {
		i -= len(m.Proposer)
		copy(dAtA[i:], m.Proposer)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Proposer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryOngoingProposalsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryOngoingProposalsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Proposals) > 0 {
		for _, e := range m.Proposals {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryOngoingProposalRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProposalId != 0 {
		n += 1 + sovQuery(uint64(m.ProposalId))
	}
	return n
}

func (m *QueryOngoingProposalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Proposer)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if len(m.Amount) > 0 {
		for _, e := range m.Amount {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryOngoingProposalsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryOngoingProposalsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryOngoingProposalsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryOngoingProposalsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryOngoingProposalsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryOngoingProposalsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proposals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proposals = append(m.Proposals, BurnProposal{})
			if err := m.Proposals[len(m.Proposals)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryOngoingProposalRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryOngoingProposalRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryOngoingProposalRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposalId", wireType)
			}
			m.ProposalId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProposalId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryOngoingProposalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryOngoingProposalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryOngoingProposalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proposer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proposer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = append(m.Amount, types.Coin{})
			if err := m.Amount[len(m.Amount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
