/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../../common/index.js";
  

  export interface DelegationManagerInterface extends Interface {
    getFunction(nameOrSignature: "delegations" | "unbondingDelegations"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'delegations', values: [AddressLike, string]): string;
encodeFunctionData(functionFragment: 'unbondingDelegations', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'delegations', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unbondingDelegations', data: BytesLike): Result;
  }

  

  export interface DelegationManager extends BaseContract {
    
    connect(runner?: ContractRunner | null): DelegationManager;
    waitForDeployment(): Promise<this>;

    interface: DelegationManagerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    delegations: TypedContractMethod<
      [arg0: AddressLike, arg1: string, ],
      [bigint],
      'view'
    >
    

    
    unbondingDelegations: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [[string, bigint, bigint, bigint] & {validator: string, amount: bigint, creationHeight: bigint, completionTime: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'delegations'): TypedContractMethod<
      [arg0: AddressLike, arg1: string, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'unbondingDelegations'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [[string, bigint, bigint, bigint] & {validator: string, amount: bigint, creationHeight: bigint, completionTime: bigint }],
      'view'
    >;

    

    filters: {
      
    };
  }