/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { PayableOverrides } from "../../../../../common/index.js";
  import type { Transferer, TransfererInterface } from "../../../../../cosmos/testutil/contracts/Reverter.sol/Transferer";

  const _abi = [
  {
    "inputs": [],
    "stateMutability": "payable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "withdraw",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608060405260b3806100126000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80633ccfd60b14602d575b600080fd5b60336035565b005b3373ffffffffffffffffffffffffffffffffffffffff166108fc479081150290604051600060405180830381858888f19350505050158015607a573d6000803e3d6000fd5b5056fea2646970667358221220b1ddd8e971e8134e06b0b1ed32d277c428b156c9b91bb8be083f9c9a9570bd2564736f6c63430008120033";

  
      type TransfererConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: TransfererConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class Transferer__factory extends ContractFactory {
    
      constructor(...args: TransfererConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: PayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: PayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<Transferer & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): Transferer__factory {
      return super.connect(runner) as Transferer__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): TransfererInterface {
      return new Interface(_abi) as TransfererInterface;
    }
    
    override attach(address: string | Addressable): Transferer {
      return super.attach(address) as Transferer;
    }
  static connect(address: string, runner?: ContractRunner | null): Transferer {
      return new Contract(address, _abi, runner) as unknown as Transferer;
    }
  }

  
  