/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ICounter, ICounterInterface } from "../../../../cosmos/testutil/contracts/ICounter";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "counter",
        "type": "uint256"
      }
    ],
    "name": "Added",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "counter",
        "type": "uint256"
      }
    ],
    "name": "Changed",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "add",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getCounter",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "subtract",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class ICounter__factory {
    static readonly abi = _abi;
    static createInterface(): ICounterInterface {
      return new Interface(_abi) as ICounterInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ICounter {
      return new Contract(address, _abi, runner) as unknown as ICounter;
    }
  }
  