/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PrecompileWrapper } from './PrecompileWrapper';
export type { RevertTestContract } from './RevertTestContract';