/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common/index.js";
  

  export interface PrecompileWrapperInterface extends Interface {
    getFunction(nameOrSignature: "wrappedDistributionCall" | "wrappedOutOfGasCall" | "wrappedStakingCall"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "WrapperCall"): EventFragment;

    encodeFunctionData(functionFragment: 'wrappedDistributionCall', values: [string]): string;
encodeFunctionData(functionFragment: 'wrappedOutOfGasCall', values: [string]): string;
encodeFunctionData(functionFragment: 'wrappedStakingCall', values: [string, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'wrappedDistributionCall', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'wrappedOutOfGasCall', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'wrappedStakingCall', data: BytesLike): Result;
  }

  
    export namespace WrapperCallEvent {
      export type InputTuple = [operation: string, success: boolean];
      export type OutputTuple = [operation: string, success: boolean];
      export interface OutputObject {operation: string, success: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PrecompileWrapper extends BaseContract {
    
    connect(runner?: ContractRunner | null): PrecompileWrapper;
    waitForDeployment(): Promise<this>;

    interface: PrecompileWrapperInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    wrappedDistributionCall: TypedContractMethod<
      [validatorAddress: string, ],
      [void],
      'nonpayable'
    >
    

    
    wrappedOutOfGasCall: TypedContractMethod<
      [validatorAddress: string, ],
      [void],
      'nonpayable'
    >
    

    
    wrappedStakingCall: TypedContractMethod<
      [validatorAddress: string, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'wrappedDistributionCall'): TypedContractMethod<
      [validatorAddress: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'wrappedOutOfGasCall'): TypedContractMethod<
      [validatorAddress: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'wrappedStakingCall'): TypedContractMethod<
      [validatorAddress: string, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'WrapperCall'): TypedContractEvent<WrapperCallEvent.InputTuple, WrapperCallEvent.OutputTuple, WrapperCallEvent.OutputObject>;

    filters: {
      
      'WrapperCall(string,bool)': TypedContractEvent<WrapperCallEvent.InputTuple, WrapperCallEvent.OutputTuple, WrapperCallEvent.OutputObject>;
      WrapperCall: TypedContractEvent<WrapperCallEvent.InputTuple, WrapperCallEvent.OutputTuple, WrapperCallEvent.OutputObject>;
    
    };
  }