/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common/index.js";
  

  export interface RevertTestContractInterface extends Interface {
    getFunction(nameOrSignature: "counter" | "directBankRevert" | "directDistributionRevert" | "directStakingOutOfGas" | "directStakingRevert" | "getCounter" | "internalStakingCall" | "precompileViaContractOutOfGas" | "precompileViaContractRevert" | "resetCounter" | "withdraw" | "wrappedPrecompileOutOfGas"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OutOfGasSimulated" | "PrecompileCallMade"): EventFragment;

    encodeFunctionData(functionFragment: 'counter', values?: undefined): string;
encodeFunctionData(functionFragment: 'directBankRevert', values?: undefined): string;
encodeFunctionData(functionFragment: 'directDistributionRevert', values: [string]): string;
encodeFunctionData(functionFragment: 'directStakingOutOfGas', values: [string]): string;
encodeFunctionData(functionFragment: 'directStakingRevert', values: [string]): string;
encodeFunctionData(functionFragment: 'getCounter', values?: undefined): string;
encodeFunctionData(functionFragment: 'internalStakingCall', values: [string]): string;
encodeFunctionData(functionFragment: 'precompileViaContractOutOfGas', values: [string]): string;
encodeFunctionData(functionFragment: 'precompileViaContractRevert', values: [string]): string;
encodeFunctionData(functionFragment: 'resetCounter', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdraw', values?: undefined): string;
encodeFunctionData(functionFragment: 'wrappedPrecompileOutOfGas', values: [string]): string;

    decodeFunctionResult(functionFragment: 'counter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'directBankRevert', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'directDistributionRevert', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'directStakingOutOfGas', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'directStakingRevert', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCounter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'internalStakingCall', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'precompileViaContractOutOfGas', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'precompileViaContractRevert', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resetCounter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'wrappedPrecompileOutOfGas', data: BytesLike): Result;
  }

  
    export namespace OutOfGasSimulatedEvent {
      export type InputTuple = [gasLeft: BigNumberish];
      export type OutputTuple = [gasLeft: bigint];
      export interface OutputObject {gasLeft: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PrecompileCallMadeEvent {
      export type InputTuple = [precompileName: string, success: boolean];
      export type OutputTuple = [precompileName: string, success: boolean];
      export interface OutputObject {precompileName: string, success: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface RevertTestContract extends BaseContract {
    
    connect(runner?: ContractRunner | null): RevertTestContract;
    waitForDeployment(): Promise<this>;

    interface: RevertTestContractInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    counter: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    directBankRevert: TypedContractMethod<
      [],
      [void],
      'view'
    >
    

    
    directDistributionRevert: TypedContractMethod<
      [invalidValidator: string, ],
      [void],
      'nonpayable'
    >
    

    
    directStakingOutOfGas: TypedContractMethod<
      [validatorAddress: string, ],
      [void],
      'nonpayable'
    >
    

    
    directStakingRevert: TypedContractMethod<
      [invalidValidator: string, ],
      [void],
      'nonpayable'
    >
    

    
    getCounter: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    internalStakingCall: TypedContractMethod<
      [validatorAddress: string, ],
      [void],
      'nonpayable'
    >
    

    
    precompileViaContractOutOfGas: TypedContractMethod<
      [validatorAddress: string, ],
      [void],
      'nonpayable'
    >
    

    
    precompileViaContractRevert: TypedContractMethod<
      [invalidValidator: string, ],
      [void],
      'nonpayable'
    >
    

    
    resetCounter: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    withdraw: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    wrappedPrecompileOutOfGas: TypedContractMethod<
      [validatorAddress: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'counter'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'directBankRevert'): TypedContractMethod<
      [],
      [void],
      'view'
    >;
getFunction(nameOrSignature: 'directDistributionRevert'): TypedContractMethod<
      [invalidValidator: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'directStakingOutOfGas'): TypedContractMethod<
      [validatorAddress: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'directStakingRevert'): TypedContractMethod<
      [invalidValidator: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getCounter'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'internalStakingCall'): TypedContractMethod<
      [validatorAddress: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'precompileViaContractOutOfGas'): TypedContractMethod<
      [validatorAddress: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'precompileViaContractRevert'): TypedContractMethod<
      [invalidValidator: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resetCounter'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'wrappedPrecompileOutOfGas'): TypedContractMethod<
      [validatorAddress: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'OutOfGasSimulated'): TypedContractEvent<OutOfGasSimulatedEvent.InputTuple, OutOfGasSimulatedEvent.OutputTuple, OutOfGasSimulatedEvent.OutputObject>;
getEvent(key: 'PrecompileCallMade'): TypedContractEvent<PrecompileCallMadeEvent.InputTuple, PrecompileCallMadeEvent.OutputTuple, PrecompileCallMadeEvent.OutputObject>;

    filters: {
      
      'OutOfGasSimulated(uint256)': TypedContractEvent<OutOfGasSimulatedEvent.InputTuple, OutOfGasSimulatedEvent.OutputTuple, OutOfGasSimulatedEvent.OutputObject>;
      OutOfGasSimulated: TypedContractEvent<OutOfGasSimulatedEvent.InputTuple, OutOfGasSimulatedEvent.OutputTuple, OutOfGasSimulatedEvent.OutputObject>;
    

      'PrecompileCallMade(string,bool)': TypedContractEvent<PrecompileCallMadeEvent.InputTuple, PrecompileCallMadeEvent.OutputTuple, PrecompileCallMadeEvent.OutputObject>;
      PrecompileCallMade: TypedContractEvent<PrecompileCallMadeEvent.InputTuple, PrecompileCallMadeEvent.OutputTuple, PrecompileCallMadeEvent.OutputObject>;
    
    };
  }