/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BankXerc20DoubleSpendPoC } from './BankXerc20DoubleSpendPoC';
export type { PoCToken } from './PoCToken';